import * as readline from "readline";
import { mkdirSync, writeFileSync, existsSync } from "fs";
import { resolve } from "path";
import { homedir } from "os";

const CYAN = "\x1b[36m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const RESET = "\x1b[0m";

export const CONFIG_DIR = resolve(homedir(), ".gemini-chrome");
export const CONFIG_FILE = resolve(CONFIG_DIR, "config.env");

const MODELS = [
  { name: "gemini-2.5-flash", desc: "Fast + smart (recommended)" },
  { name: "gemini-2.5-pro", desc: "Most capable, slower" },
  { name: "gemini-2.0-flash", desc: "Fast, older generation" },
];

function ask(
  rl: readline.Interface,
  question: string
): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

export function isFirstRun(): boolean {
  return !existsSync(CONFIG_FILE);
}

export async function runSetup(): Promise<void> {
  console.log(`
${BOLD}${CYAN}  ╭─────────────────────────────────────╮
  │   Gemini in Chrome — Setup           │
  ╰─────────────────────────────────────╯${RESET}
`);
  console.log(`${DIM}  First time? Let's get you set up.${RESET}\n`);

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  // 1. API Key
  console.log(
    `${CYAN}  1.${RESET} Get a Gemini API key at: ${BOLD}https://aistudio.google.com/apikey${RESET}\n`
  );
  let apiKey = "";
  while (!apiKey) {
    apiKey = await ask(rl, `${BOLD}  API Key: ${RESET}`);
    if (!apiKey) {
      console.log(`${YELLOW}  API key is required.${RESET}`);
    }
  }

  // 2. Model selection
  console.log(`\n${CYAN}  2.${RESET} Choose a model:\n`);
  MODELS.forEach((m, i) => {
    const tag = i === 0 ? ` ${GREEN}(recommended)${RESET}` : "";
    console.log(`     ${BOLD}[${i + 1}]${RESET} ${m.name} — ${DIM}${m.desc}${RESET}${tag}`);
  });
  console.log("");

  let modelChoice = "";
  let model = MODELS[0].name;
  while (true) {
    modelChoice = await ask(rl, `${BOLD}  Choice [1]: ${RESET}`);
    if (!modelChoice) {
      model = MODELS[0].name;
      break;
    }
    const idx = parseInt(modelChoice, 10) - 1;
    if (idx >= 0 && idx < MODELS.length) {
      model = MODELS[idx].name;
      break;
    }
    console.log(`${YELLOW}  Please enter 1-${MODELS.length}.${RESET}`);
  }

  // 3. Chrome port
  console.log(
    `\n${CYAN}  3.${RESET} Chrome remote debugging port ${DIM}(default: 9222)${RESET}\n`
  );
  const portStr = await ask(rl, `${BOLD}  Port [9222]: ${RESET}`);
  const port = portStr ? parseInt(portStr, 10) || 9222 : 9222;

  rl.close();

  // Write config
  mkdirSync(CONFIG_DIR, { recursive: true });

  const envContent = [
    `# Gemini in Chrome — configuration`,
    `# Generated by setup wizard`,
    ``,
    `GEMINI_API_KEY=${apiKey}`,
    `GEMINI_MODEL=${model}`,
    `CDP_HOST=localhost`,
    `CDP_PORT=${port}`,
    `CONTEXT_TURNS=20`,
    `SESSIONS_DIR=./sessions`,
  ].join("\n");

  writeFileSync(CONFIG_FILE, envContent + "\n");

  console.log(`\n${GREEN}  ✓ Config saved to ${CONFIG_FILE}${RESET}`);
  console.log(`${DIM}  You can edit this file anytime to change settings.${RESET}`);

  // Show Chrome launch hint
  console.log(`
${CYAN}  To use browser features, launch Chrome with:${RESET}

  ${DIM}/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome \\
    --remote-debugging-port=${port}${RESET}
`);
}
